# Generated by Django 4.2.6 on 2023-11-06 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('rok_vyroby', models.IntegerField(validators=[django.core.validators.MinValueValidator(1880), django.core.validators.MaxValueValidator(2050)])),
            ],
        ),
    ]
