# Generated by Django 5.0 on 2024-01-04 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cena',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='model',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='auto',
            name='znacka',
            field=models.CharField(max_length=25),
        ),
    ]
