# Generated by Django 4.2.6 on 2023-11-27 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0002_rezervace'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cena',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
