# Generated by Django 5.0 on 2023-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0003_auto_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='img',
            field=models.CharField(default='https://i.ibb.co/MS9JRPK/image.png', max_length=200),
            preserve_default=False,
        ),
    ]
