# Generated by Django 5.0 on 2024-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0003_rezervace_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
