# Generated by Django 5.0 on 2024-01-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0004_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('order', models.IntegerField(default=1)),
                ('auto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.auto')),
            ],
            options={
                'verbose_name': 'Poznámka',
                'verbose_name_plural': 'Poznámky',
            },
        ),
    ]
