# Generated by Django 5.0 on 2023-12-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0005_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
    ]
