# Generated by Django 5.0 on 2024-02-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0005_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
