# Generated by Django 5.0 on 2023-12-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
