# Generated by Django 5.0 on 2024-02-19 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0006_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cena',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='rok_vyroby',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
