# Generated by Django 5.0 on 2024-02-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0008_alter_image_auto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='motor',
        ),
    ]
