# Generated by Django 5.0 on 2023-12-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0008_alter_auto_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('auto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.auto')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='images',
            field=models.ManyToManyField(blank=True, to='auta.image'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('order', models.IntegerField(default=0)),
                ('auto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.auto')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='notes',
            field=models.ManyToManyField(blank=True, to='auta.note'),
        ),
    ]
