# Generated by Django 5.0 on 2023-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0012_remove_auto_images_remove_auto_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
