# Generated by Django 5.0 on 2023-12-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0014_alter_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='img',
        ),
    ]
